name: Build Patch_VietHoa.exe

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        python --version
        pip install pyinstaller

    - name: Build executable
      run: |
        cd tools
        pyinstaller --onefile --noconsole --version-file=version_info.txt Patch_VietHoa.py

    - name: Show SHA256 of built exe
      run: |
        Get-FileHash .\tools\dist\Patch_VietHoa.exe -Algorithm SHA256

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: Patch_VietHoa
        path: tools/dist/Patch_VietHoa.exe
